nodeLinker: node-modules
logFilters:
  - code: YN0002
    level: discard
  - code: YN0013
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
